pr fix troubleshoot
fdnd-agency/crossmarx pull request #28
Opened 2024-05-16 22:07 UTC by fatihg61

## What does this change?

resolves the issues made in the PR of zenit

Vercel deploymeny error waardoor geen livelink. Zal dit morgen met Zenit oplossen!

## How Has This Been Tested?

- [ ] User test
- [ ] Accessibility test
- [ x] Performance test
- [ x] Responsive Design test
- [ x] Device test
- [ x] Browser test

## Images

zie https://github.com/zenitba/FDNDStrandeiland/pull/101#issuecomment-2116274850

## How to review

Responsive test with activity bar
check of filter works with livelink when online

2024-05-21 08:27 UTC, ju5tu5 requested changes

2024-05-21 08:27 UTC, ju5tu5 commented on src/lib/atoms/Levels.svelte
> +		<svg class="icon icon-risk" viewBox="0 0 24 24" width="20" height="20">
Mag de SVG naar een extern bestand in de lib? ik denk een atom...

2024-05-21 08:27 UTC, ju5tu5 commented on src/lib/atoms/Levels.svelte
> +		<svg class="icon icon-heart" viewBox="0 0 24 24" width="20" height="20">
Same here..

2024-05-21 08:27 UTC, ju5tu5 commented on src/lib/molecule/Filter.svelte
> +			<svg
extern bestand plx

2024-05-21 08:27 UTC, ju5tu5 commented on src/lib/molecule/Roll.svelte
> +	function countClicks2() {
Ik denk dat je deze functie kunt abstraheren.. iets verderop staat countClicks3 die nagenoeg hetzelfde doet. Je herhaalt jezelf ;)

2024-05-21 08:27 UTC, ju5tu5 commented on src/lib/molecule/Roll.svelte
> +	  setTimeout(() => {
Zelfde als de setTimeout.. die zie ik drie keer op bijna dezelfde manier.. een functie is dan logischer..

2024-05-21 08:27 UTC, ju5tu5 commented on src/routes/+page.svelte
Probeer al je componenten in ```$lib/index.js``` neer te zetten.. je import statement wordt dan veel netter: ```import {Loader, Navbar, Hero, ...} from '$lib/index'

2024-05-21 08:27 UTC, ju5tu5 commented on src/routes/overzicht/+page.svelte
Same als hierboven...

2024-05-21 08:27 UTC, ju5tu5 commented on src/routes/overzicht/wens/[id]/+page.svelte
Same als hierboven...

2024-05-22 08:28 UTC, zenitba commented
Dankjewel voor de feedback ze zijn verwerkt.
Sorry nog geen livelink heb deploy problemen
[Feedback verwerkt](https://github.com/zenitba/FDNDStrandeiland/issues/109)

2024-05-22 09:37 UTC, fatihg61 commented
@ju5tu5 @joostf kunnen we vandaag een merge verwachten?

2024-05-23 11:26 UTC, joostf requested changes
Paar kleine issues alvast, en verder kan ik pas goed testen met de live link

2024-05-23 11:26 UTC, joostf commented on src/lib/Molecul/Filter.svelte
> +<div class="filter-controls">
Waarom is dit een _div_ en geen _form_ element?

2024-05-23 11:26 UTC, joostf commented on src/lib/Organism/Footer.svelte
De _section_ elementen missen headings (h2, h3, ...). Als die worden toegevoegd iwordt al gauw duidelijk of de structuur van de HTML wel klopt.

2024-05-28 09:37 UTC, zenitba commented
live link doet het weer.
https://fdnd-strandeiland.vercel.app/

2024-05-28 09:40 UTC, zenitba commented on src/lib/Organism/Footer.svelte
toegevoegd
```html
<h2>Contact en Informatie</h2> 
```

2024-05-29 13:27 UTC, fatihg61 commented
Added changes: from div to form.
ATM trying to implement form action en GET for filtering without JS

2025-09-23 16:20 UTC, closed without merging